allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  argon2: true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  'postcss@<8.5.10': ^8.5.14
  '@hono/node-server@<1.19.13': ^1.19.13
