import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  _clearVaultForTests,
  isVaultToken,
  resolveVaultToken,
  storeApiKey,
} from "@/server/prowlarr-key-vault";

beforeEach(() => {
  vi.unstubAllEnvs();
  _clearVaultForTests();
});

afterEach(() => {
  vi.unstubAllEnvs();
  _clearVaultForTests();
  vi.useRealTimers();
});

describe("isVaultToken", () => {
  it("recognises tokens generated by the vault", () => {
    const token = storeApiKey("real-key");
    expect(isVaultToken(token)).toBe(true);
  });

  it("rejects strings that do not start with the prefix", () => {
    expect(isVaultToken("real-key")).toBe(false);
    expect(isVaultToken("")).toBe(false);
    expect(isVaultToken("ua_key:abc")).toBe(false);
  });
});

describe("storeApiKey + resolveVaultToken", () => {
  it("round-trips a real key through a vault token", () => {
    const token = storeApiKey("real-key-xyz");
    expect(resolveVaultToken(token)).toBe("real-key-xyz");
  });

  it("hands out a unique token per call", () => {
    const a = storeApiKey("k");
    const b = storeApiKey("k");
    expect(a).not.toEqual(b);
  });

  it("returns null for an unknown token", () => {
    expect(resolveVaultToken("__ua_key:never-stored")).toBeNull();
  });

  it("expires entries after 15 minutes", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-01-01T00:00:00Z"));
    const token = storeApiKey("ephemeral");
    expect(resolveVaultToken(token)).toBe("ephemeral");

    vi.setSystemTime(new Date("2026-01-01T00:14:59Z"));
    expect(resolveVaultToken(token)).toBe("ephemeral");

    vi.setSystemTime(new Date("2026-01-01T00:15:01Z"));
    expect(resolveVaultToken(token)).toBeNull();
  });
});

describe("_clearVaultForTests", () => {
  it("removes all entries", () => {
    const t = storeApiKey("k");
    _clearVaultForTests();
    expect(resolveVaultToken(t)).toBeNull();
  });

  it("refuses to run in production", () => {
    vi.stubEnv("NODE_ENV", "production");
    expect(() => _clearVaultForTests()).toThrow(
      /must not be called in production/,
    );
  });
});
